spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/singlepointauth"
    username: "root"
    password : "welcome123$"

  jpa:
    hibernate.ddl-auto: "none"
    hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
    show-sql: "true"